[package]
name = "atlas-mirror-crates"
version = "0.77.1"
edition = "2021"
license = "MIT"

[[bin]]
name = "atlas-mirror-crates"
path = "src/main.rs"

[dependencies]
atlas-common = { path = "../common" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
